In [1]:
# read taxi_zones.shp geojson
import geopandas as gpd
import pandas as pd

In [2]:
import geopandas as gpd

# Load the shapefile
taxi_zones = gpd.read_file("taxi_zones/taxi_zones.shp")

# Convert to a projected CRS (e.g., EPSG:3857 - Web Mercator, good for NYC)
taxi_zones_projected = taxi_zones.to_crs(epsg=3857)

# Compute centroids in the projected CRS
taxi_zones_projected['centroid'] = taxi_zones_projected['geometry'].centroid

# Convert back to geographic CRS (WGS84 - EPSG:4326)
taxi_zones = taxi_zones_projected.to_crs(epsg=4326)

# Convert centroid column to EPSG:4326 as well
taxi_zones['centroid'] = taxi_zones_projected['centroid'].to_crs(epsg=4326)
taxi_zones

,OBJECTID,Shape_Leng,Shape_Area,zone,LocationID,borough,geometry,centroid
0,1,0.116357,0.000782,Newark Airport,1,EWR,"POLYGON ((-74.18445 40.69500, -74.18449 40.695...",POINT (-74.17400 40.69183)
1,2,0.433470,0.004866,Jamaica Bay,2,Queens,"MULTIPOLYGON (((-73.82338 40.63899, -73.82277 ...",POINT (-73.83130 40.61675)
2,3,0.084341,0.000314,Allerton/Pelham Gardens,3,Bronx,"POLYGON ((-73.84793 40.87134, -73.84725 40.870...",POINT (-73.84742 40.86447)
3,4,0.043567,0.000112,Alphabet City,4,Manhattan,"POLYGON ((-73.97177 40.72582, -73.97179 40.725...",POINT (-73.97697 40.72375)
4,5,0.092146,0.000498,Arden Heights,5,Staten Island,"POLYGON ((-74.17422 40.56257, -74.17349 40.562...",POINT (-74.18848 40.55266)
...,...,...,...,...,...,...,...,...
258,259,0.126750,0.000395,Woodlawn/Wakefield,259,Bronx,"POLYGON ((-73.85107 40.91037, -73.85207 40.909...",POINT (-73.85222 40.89793)
259,260,0.133514,0.000422,Woodside,260,Queens,"POLYGON ((-73.90175 40.76078, -73.90147 40.759...",POINT (-73.90631 40.74424)
260,261,0.027120,0.000034,World Trade Center,261,Manhattan,"POLYGON ((-74.01333 40.70503, -74.01327 40.704...",POINT (-74.01302 40.70914)
261,262,0.049064,0.000122,Yorkville East,262,Manhattan,"MULTIPOLYGON (((-73.94383 40.78286, -73.94376 ...",POINT (-73.94651 40.77593)
262,263,0.037017,0.000066,Yorkville West,263,Manhattan,"POLYGON ((-73.95219 40.77302, -73.95269 40.772...",POINT (-73.95101 40.77877)

In [ ]:
# Display the GeoDataFrame
taxi_zones = taxi_zones[['LocationID', 'centroid']]

results = []
for idx, row in taxi_zones.iterrows():
    results.append([row['LocationID'], row['centroid'].x, row['centroid'].y])

results

In [55]:
# write results to csv
import csv
with open('taxi_zones_centroids.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["LocationID", "Longitude", "Latitude"])
    writer.writerows(results)

# NOTE! LOCATION ID == 57 is missing and ID == 56 is duplicated, manually correct after generating the file

# LOCATION 103 has 3. 104 and 105 is missing. Manually fix